// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3frPE6VlBzQiERnuCnPkvW_c19kLDWE',
    appId: '1:109635408292:web:e89a9c268c10189321b131',
    messagingSenderId: '109635408292',
    projectId: 'lingo-learn-28dab',
    authDomain: 'lingo-learn-28dab.firebaseapp.com',
    storageBucket: 'lingo-learn-28dab.firebasestorage.app',
    measurementId: 'G-WHXQRPEX2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yKGbvIJCNqa960sTkZnxjYuTyIMhaus',
    appId: '1:109635408292:android:e3265701e555f59b21b131',
    messagingSenderId: '109635408292',
    projectId: 'lingo-learn-28dab',
    storageBucket: 'lingo-learn-28dab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgrTRCJD6GoyTYaNfzo2xdwTSklWPUWc',
    appId: '1:109635408292:ios:c993e60fb0daf78c21b131',
    messagingSenderId: '109635408292',
    projectId: 'lingo-learn-28dab',
    storageBucket: 'lingo-learn-28dab.firebasestorage.app',
    iosBundleId: 'com.example.lingoLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgrTRCJD6GoyTYaNfzo2xdwTSklWPUWc',
    appId: '1:109635408292:ios:c993e60fb0daf78c21b131',
    messagingSenderId: '109635408292',
    projectId: 'lingo-learn-28dab',
    storageBucket: 'lingo-learn-28dab.firebasestorage.app',
    iosBundleId: 'com.example.lingoLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG3frPE6VlBzQiERnuCnPkvW_c19kLDWE',
    appId: '1:109635408292:web:148435b874b224e321b131',
    messagingSenderId: '109635408292',
    projectId: 'lingo-learn-28dab',
    authDomain: 'lingo-learn-28dab.firebaseapp.com',
    storageBucket: 'lingo-learn-28dab.firebasestorage.app',
    measurementId: 'G-Z7ZR0D39VW',
  );
}
